language:
  - "python"

python:
  - "2.7"

install:
  -  "pip install -r requirements.txt"
  -  "pip install pytest"

script:
  -  "git clone https://github.com/django/django.git --depth=1"
  -  "mkdir ~/dev"
  -  "mv django ~/dev/django"
  -  "fab populate_redis"
  -  "./run_tests.sh"

services:
  - redis-server

notifications:
  email:
    recipients:
      - papaloizouc@gmail.com
    on_success: change
    on_failure: always
